export type ThemeName = "zinc" | "slate" | "rose" | "emerald" | "amber";

export type ThemeVars = Record<string, string>;

export type Theme = {
  name: ThemeName;
  label: string;
  swatch: string;
  light: ThemeVars;
  dark: ThemeVars;
};

export const THEMES: Theme[] = [
  {
    name: "zinc",
    label: "Zinc",
    swatch: "#18181b",
    light: {
      "--background": "#ffffff",
      "--foreground": "#0a0a0a",
      "--muted": "#f4f4f5",
      "--muted-foreground": "#71717a",
      "--card": "#ffffff",
      "--card-foreground": "#0a0a0a",
      "--border": "#e4e4e7",
      "--input": "#e4e4e7",
      "--ring": "#18181b",
      "--primary": "#18181b",
      "--primary-foreground": "#fafafa",
      "--secondary": "#f4f4f5",
      "--secondary-foreground": "#18181b",
      "--accent": "#f4f4f5",
      "--accent-foreground": "#18181b",
      "--destructive": "#ef4444",
      "--destructive-foreground": "#fafafa",
      "--radius": "0.5rem",
    },
    dark: {
      "--background": "#09090b",
      "--foreground": "#fafafa",
      "--muted": "#18181b",
      "--muted-foreground": "#a1a1aa",
      "--card": "#09090b",
      "--card-foreground": "#fafafa",
      "--border": "#27272a",
      "--input": "#27272a",
      "--ring": "#d4d4d8",
      "--primary": "#fafafa",
      "--primary-foreground": "#18181b",
      "--secondary": "#27272a",
      "--secondary-foreground": "#fafafa",
      "--accent": "#27272a",
      "--accent-foreground": "#fafafa",
      "--destructive": "#7f1d1d",
      "--destructive-foreground": "#fafafa",
    },
  },
  {
    name: "slate",
    label: "Slate",
    swatch: "#0f172a",
    light: {
      "--background": "#ffffff",
      "--foreground": "#020617",
      "--muted": "#f1f5f9",
      "--muted-foreground": "#64748b",
      "--card": "#ffffff",
      "--card-foreground": "#020617",
      "--border": "#e2e8f0",
      "--input": "#e2e8f0",
      "--ring": "#0f172a",
      "--primary": "#0f172a",
      "--primary-foreground": "#f8fafc",
      "--secondary": "#f1f5f9",
      "--secondary-foreground": "#0f172a",
      "--accent": "#f1f5f9",
      "--accent-foreground": "#0f172a",
      "--destructive": "#ef4444",
      "--destructive-foreground": "#f8fafc",
      "--radius": "0.5rem",
    },
    dark: {
      "--background": "#020617",
      "--foreground": "#f8fafc",
      "--muted": "#0f172a",
      "--muted-foreground": "#94a3b8",
      "--card": "#020617",
      "--card-foreground": "#f8fafc",
      "--border": "#1e293b",
      "--input": "#1e293b",
      "--ring": "#cbd5e1",
      "--primary": "#f8fafc",
      "--primary-foreground": "#0f172a",
      "--secondary": "#1e293b",
      "--secondary-foreground": "#f8fafc",
      "--accent": "#1e293b",
      "--accent-foreground": "#f8fafc",
      "--destructive": "#7f1d1d",
      "--destructive-foreground": "#f8fafc",
    },
  },
  {
    name: "rose",
    label: "Rose",
    swatch: "#e11d48",
    light: {
      "--background": "#ffffff",
      "--foreground": "#1f0a10",
      "--muted": "#fff1f2",
      "--muted-foreground": "#9f1239",
      "--card": "#ffffff",
      "--card-foreground": "#1f0a10",
      "--border": "#fecdd3",
      "--input": "#fecdd3",
      "--ring": "#e11d48",
      "--primary": "#e11d48",
      "--primary-foreground": "#fff1f2",
      "--secondary": "#fff1f2",
      "--secondary-foreground": "#9f1239",
      "--accent": "#ffe4e6",
      "--accent-foreground": "#9f1239",
      "--destructive": "#dc2626",
      "--destructive-foreground": "#fff1f2",
      "--radius": "0.625rem",
    },
    dark: {
      "--background": "#18060a",
      "--foreground": "#ffe4e6",
      "--muted": "#2a0b12",
      "--muted-foreground": "#fb7185",
      "--card": "#1f0810",
      "--card-foreground": "#ffe4e6",
      "--border": "#3f0d18",
      "--input": "#3f0d18",
      "--ring": "#fb7185",
      "--primary": "#fb7185",
      "--primary-foreground": "#1f0810",
      "--secondary": "#2a0b12",
      "--secondary-foreground": "#ffe4e6",
      "--accent": "#2a0b12",
      "--accent-foreground": "#ffe4e6",
      "--destructive": "#7f1d1d",
      "--destructive-foreground": "#ffe4e6",
    },
  },
  {
    name: "emerald",
    label: "Emerald",
    swatch: "#059669",
    light: {
      "--background": "#ffffff",
      "--foreground": "#022c22",
      "--muted": "#ecfdf5",
      "--muted-foreground": "#047857",
      "--card": "#ffffff",
      "--card-foreground": "#022c22",
      "--border": "#a7f3d0",
      "--input": "#a7f3d0",
      "--ring": "#059669",
      "--primary": "#059669",
      "--primary-foreground": "#ecfdf5",
      "--secondary": "#ecfdf5",
      "--secondary-foreground": "#064e3b",
      "--accent": "#d1fae5",
      "--accent-foreground": "#064e3b",
      "--destructive": "#ef4444",
      "--destructive-foreground": "#ecfdf5",
      "--radius": "0.5rem",
    },
    dark: {
      "--background": "#021812",
      "--foreground": "#d1fae5",
      "--muted": "#052e22",
      "--muted-foreground": "#34d399",
      "--card": "#03241a",
      "--card-foreground": "#d1fae5",
      "--border": "#064e3b",
      "--input": "#064e3b",
      "--ring": "#34d399",
      "--primary": "#34d399",
      "--primary-foreground": "#03241a",
      "--secondary": "#064e3b",
      "--secondary-foreground": "#d1fae5",
      "--accent": "#064e3b",
      "--accent-foreground": "#d1fae5",
      "--destructive": "#7f1d1d",
      "--destructive-foreground": "#d1fae5",
    },
  },
  {
    name: "amber",
    label: "Amber",
    swatch: "#d97706",
    light: {
      "--background": "#fffbeb",
      "--foreground": "#1c1207",
      "--muted": "#fef3c7",
      "--muted-foreground": "#92400e",
      "--card": "#ffffff",
      "--card-foreground": "#1c1207",
      "--border": "#fde68a",
      "--input": "#fde68a",
      "--ring": "#d97706",
      "--primary": "#d97706",
      "--primary-foreground": "#fffbeb",
      "--secondary": "#fef3c7",
      "--secondary-foreground": "#78350f",
      "--accent": "#fde68a",
      "--accent-foreground": "#78350f",
      "--destructive": "#dc2626",
      "--destructive-foreground": "#fffbeb",
      "--radius": "0.75rem",
    },
    dark: {
      "--background": "#180f03",
      "--foreground": "#fef3c7",
      "--muted": "#2a1c08",
      "--muted-foreground": "#fbbf24",
      "--card": "#1f1305",
      "--card-foreground": "#fef3c7",
      "--border": "#451a03",
      "--input": "#451a03",
      "--ring": "#fbbf24",
      "--primary": "#fbbf24",
      "--primary-foreground": "#1f1305",
      "--secondary": "#2a1c08",
      "--secondary-foreground": "#fef3c7",
      "--accent": "#2a1c08",
      "--accent-foreground": "#fef3c7",
      "--destructive": "#7f1d1d",
      "--destructive-foreground": "#fef3c7",
    },
  },
];

export function themeToCss(theme: Theme): string {
  const vars = (obj: ThemeVars) =>
    Object.entries(obj)
      .map(([k, v]) => `  ${k}: ${v};`)
      .join("\n");
  return `:root {\n${vars(theme.light)}\n}\n\n.dark {\n${vars(theme.dark)}\n}\n`;
}
