export const registry = [
  { slug: "button", name: "Button", description: "Clickable button with variants, sizes, loading state." },
  { slug: "badge", name: "Badge", description: "Label for status or category." },
  { slug: "card", name: "Card", description: "Container with header, content, footer." },
  { slug: "input", name: "Input", description: "Text input field." },
  { slug: "label", name: "Label", description: "Form field label." },
  { slug: "separator", name: "Separator", description: "Horizontal or vertical divider." },
  { slug: "skeleton", name: "Skeleton", description: "Loading placeholder." },
  { slug: "spinner", name: "Spinner", description: "Loading indicator." },
  { slug: "textarea", name: "Textarea", description: "Multi-line text input." },
  { slug: "checkbox", name: "Checkbox", description: "Binary toggle input." },
  { slug: "radio", name: "Radio", description: "Single-choice from group." },
  { slug: "switch", name: "Switch", description: "On/off toggle." },
  { slug: "select", name: "Select", description: "Dropdown single-select with keyboard nav." },
  { slug: "portal", name: "Portal", description: "Render children into document.body." },
  { slug: "dialog", name: "Dialog", description: "Modal overlay with focus trap." },
  { slug: "confirm-modal", name: "ConfirmModal", description: "Confirm/cancel modal." },
  { slug: "sheet", name: "Sheet", description: "Side-anchored slide-out panel." },
  { slug: "popover", name: "Popover", description: "Floating panel anchored to trigger." },
  { slug: "tooltip", name: "Tooltip", description: "Hover hint." },
  { slug: "dropdown-menu", name: "DropdownMenu", description: "Menu with keyboard nav." },
  { slug: "toast", name: "Toast", description: "Imperative notification via custom store." },
  { slug: "alert", name: "Alert", description: "Inline status message." },
  { slug: "avatar", name: "Avatar", description: "User image with fallback initials." },
  { slug: "progress", name: "Progress", description: "Linear progress bar." },
  { slug: "breadcrumb", name: "Breadcrumb", description: "Hierarchy navigation." },
  { slug: "pagination", name: "Pagination", description: "Paged navigation with siblings." },
  { slug: "empty-state", name: "EmptyState", description: "Placeholder for empty views." },
  { slug: "tabs", name: "Tabs", description: "Tab panels." },
  { slug: "accordion", name: "Accordion", description: "Collapsible sections." },
  { slug: "table", name: "Table", description: "Semantic table primitives." },
  { slug: "sidebar", name: "Sidebar", description: "Collapsible app sidebar." },
  { slug: "combobox", name: "Combobox", description: "Searchable single-select." },
  { slug: "calendar", name: "Calendar", description: "Month calendar (date-fns)." },
  { slug: "date-picker", name: "DatePicker", description: "Date input with calendar popover." },
  { slug: "command-palette", name: "CommandPalette", description: "Cmd+K fuzzy search (cmdk)." },
  { slug: "data-table", name: "DataTable", description: "Sortable filterable paginated table (@tanstack/react-table)." },
] as const;

export type ComponentSlug = (typeof registry)[number]["slug"];
